### ISSUE TITLE
Povprečje tabele

### ISSUE THREAD

**Issue by anamavsenik** [anamkravanja/APPR-2017-18#2]
Pozdravljeni, 

v uvozu sem uvozila tabelo povprecne_place_po_statisticnih_regijah, potem pa jo spremenila v povpr.place.stat.reg.. Zanima me, na kakšen način lahko iz te tabele izračunam povprečje od vseh let, ki so v tabeli za posamezno regijo, pri čemer pri posameznem letu upoštevam samo spol-SKUPAJ in starost-SKUPAJ. Torej bo nova tabela vsebovala le stolpec regije in stolpec povprečje, kar bom uporabila pri vizualizaciji. 

Najlepša hvala in lep pozdrav, 
Ana Marija Kravanja

**Comment by jaanos** [comment]
Najprej bo treba poskrbeti za pretvorbo stolpca `povpr.placa` v števila - najlažje bo, če v `uvoz.r` pri prvi definiciji razpredelnice `povpr.place.stat.reg.` pri `transmute` namesto samo `povpr.placa` podaš parameter `povpr.placa = parse_number(povpr.placa)`. Podobno bo treba narediti tudi pri razpredelnici `povp.place.dejavnost`.

Sedaj lahko s `filter` izbereš želene vrstice ter nato z `group_by` in `summarise` poskrbiš za združevanje in izračun povprečja, npr.
```R
povpr.place.stat.reg.%>% filter(spol == "Spol - SKUPAJ",
                                starost == "Starost - SKUPAJ",
                                regija != "SLOVENIJA") %>%
  group_by(regija) %>% summarise(povprecje = mean(povpr.placa))
```
