### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [anamkravanja/APPR-2017-18#3]
Prosim poskrbi za svoje poročilo (`projekt.Rmd`), da boš lahko v četrtek predstavila svoj projekt. Del, ki je ostal iz vzorca, pobriši, da se ti bo poročilo prevedlo. Svetujem, da iz glave odstraniš vrstico `runtime: shiny` - po shranjevanju se bo pojavil gumb *Knit*, s katerim lahko poročilo prevedeš v obliko HTML.

Opažam še, da uvoz zemljevida pri meni ne deluje - problem je v velikosti črk pri podanem imenu datoteke v zemljevidu. Uporabi torej `"Statisticne_regije"` (z veliko začetnico), saj so nekateri sistemi občutljivi na velikost črk.

Še to: v `vizualizacija.r` ne izrisuj grafov in zemljevidov - to stori v poročilu z blokom kode na mestu, kjer želiš graf oziroma zemljevid prikazati. Iz `vizualizacija.r` prav tako odstrani del, ki je ostal iz vzorca.

**Comment by anamavsenik** [comment]
Pozdravljeni!

Zanima me še, kako se lahko v poročilu znebim napak, ki mi jih napiše. Za nekatere ste rekli, da ni pomembno tudi če so. V poročilu pa je to moteče.
Poleg tega ne vem zakaj mi zemljevid nariše 2-krat. Drugi je pravi. In na kakšen način lahko popravim prvi histogram, da bo prikazan večje, legenda pa bo manjša.

Hvala in lep pozdrav, 
Ana Marija K.

**Comment by jaanos** [comment]
Da se ti opozorila ne izpisujejo v poročilo, v glavo blokov kode, kjer se pojavijo, dodaj parameter `warning = FALSE`.

V zadnjem bloku kode izrisuješ dva zemljevida - prvega torej odstrani.

Pri tortnem diagramu lahko poskusiš zmanjšati velikost pisave v legendi, npr.
```R
dejavnost + coord_polar() + theme(legend.text = element_text(size = 5))
```

Glede na to, da ti poročilo sedaj prevede, bom kar dodal povezavo do trenutnega commita na repoztorij za zagovore. Ko boš rešila te težave in boš želela posodobiti povezavo, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-zagovori) (glej navodila spodaj).

**Comment by jaanos** [comment]
Vidim, da si naložila novo različico, tako da sem kar posodobil. Opozoril bi te še na oblikovanje samega poročila. Če želiš iti v nov odstavek, pusti prazno vrstico - enako velja tudi pred in po seznamih. Tako svetujem, da vrineš nekaj praznih vrstic v sledečem delu:

https://github.com/anamkravanja/APPR-2017-18/blob/2d16b4c6058e2fe2083a776b3eee71cbd7584e9d/projekt.Rmd#L35-L65

Prazne vrstice naj bodo pred vsako oštevilčeno točko in po njej - tako se bo ustvaril oštevilčen seznam, pod vsako točko pa še točkast seznam. Opomba ni del seznama, tako da pred njo prav tako pusti prazno vrstico. Pazi še, da zaporedni številki vedno sledi presledek - v zgornjem odseku manjka za `5.`, zato zadnja točka ni ustrezno zamaknjena.

Opozoril bi še na graf s plačami glede na izobrazbo in spol. Tukaj ni jasno, zakaj imaš več točk za vsako kombinacijo leta, izobrazbe in spola - v poročilu bo treba torej pojasniti, da različne točke predstavljajo različne sektorje. Morda bi sicer te lahko ločila že na samem grafu - lahko bi npr. dodala še črte (`geom_line`) različnih tipov (polna, pikčasta, črtasta - parameter `linetype = sektor` pri `aes`). Sama presodi, ali se ti zdi tak graf boljši ali slabši od trenutnega.
